config/routes.rb
SmileAtMe::Application.routes.draw do
  resources :users do
  	member do
  		get :favored
  	end
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :smiles, only: [:index, :create, :destroy, :show ] do
  	collection do
  		get :favorers
  	end
  end
  resources :relationships, only: [:create, :destroy]
  resources :messages, only: [:index, :create, :destroy]

  root to: "static_pages#home"

  
  match '/signup', to:'users#new', via:'get'
  
  match '/signin', to:'sessions#new', via:'get'
  match '/signout', to:'sessions#destroy', via: 'delete'

  match '/uploadtoken', to: 'qiniu_uploaders#uptoken', via: 'get'

  match '/mysmiles', to: 'static_pages#mysmiles', via: 'get'

  match '/uploadsmile', to: 'qiniu_uploaders#new', via: 'get'
  match '/deletesmile', to: 'qiniu_uploaders#delete', via: 'delete'

  match '/favorites', to: 'smiles#favorites', via: 'get'

  get ':id', :to => "users#show"

  

end

app/views/layouts/_footBanner.html.erb
  <div class="footer-banner" style="width:100%; margin:160px auto 100px"></div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation" id="navBar">
    <div class="container-fluid">

      <!-- Brand and toggle get grouped for better mobile display -->
    
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    
      <a class="navbar-brand" href="/">
        <%= image_tag("SmileAtMeLogo.png") %>
        
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav" id="navList">
        <li class="active"><a href="/">SmileWall</a></li>
        <% if signed_in? %>
        <li><a href="/<%= current_user.name %>">Me</a></li>
        <%end%>    
      </ul>

      
      
      <ul class="nav navbar-nav navbar-right">
      <% if signed_in? %> 
        
        <li id="messageIcon" type="button" data-toggle="modal" data-target="#messagePanel"><a></a></li>

        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown"><% if current_user.avatar == nil %>
                <img src="http://7u2ew1.com1.z0.glb.clouddn.com/emptyAvatar.jpg">
              <%else%>
                <img src="<%= current_user.avatar%>">  
              <%end%><span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li id="setting" type="button" data-toggle="modal" data-target="#settingPanel" ><a style="cursor: pointer"><span class="fa fa-gear"></span>&nbsp;&nbsp;Profile photo</a></li>
            
            <li class="divider"></li>
            <li><a href="/favorites" style="cursor: pointer"><span class="fa fa-heart"></span>&nbsp;&nbsp;Favorites</a></li>
            <li><a style="cursor: pointer"><span class="fa fa-pencil"></span>&nbsp;&nbsp;Suggestions</a></li>


            <li class="divider"></li>
            <li><%= link_to content_tag(:span,"  Sign out", class: "fa fa-sign-out"), signout_path, method: "delete" %></li>
          </ul>
        </li>
        
      <% else %>
        <li><a href="#" data-toggle="modal" data-target="#logIn">Login</a></li>
        <li><a href="#" data-toggle="modal" data-target="#signUp">Sign up</a></li>
      </ul>

      <% end %>


    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_imageLightBox.html.erb
	<!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
  <div id="blueimp-gallery" class="blueimp-gallery" data-use-bootstrap-modal="false">
    <!-- The container for the modal slides -->
    <div class="slides"></div>
    <!-- Controls for the borderless lightbox -->
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
    <!-- The modal dialog, which will be used to wrap the lightbox content -->
    <div class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body next"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left prev">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                        Previous
                    </button>
                    <button type="button" class="btn btn-primary next">
                        Next
                        <i class="glyphicon glyphicon-chevron-right"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_loginForm.html.erb
<div class="modal fade bs-example-modal-sm" id="logIn" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title"><b>Login</b></h4>
      </div>
      <div class="modal-body">
      <%= form_for(:session, url: sessions_path) do |f| %>
      
      <%= f.label :email, "Email:" %>
      <%= f.text_field :email, class: 'form-control logInInputControl' %><br>
      
      <%= f.label :password, "Password:" %>
      <%= f.password_field :password, class: 'form-control logInInputControl' %>
      <br>
      
      <% end %>
      
      </div>
      
    <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="sureToLogin">Login</button>
    </div>
    </div>
</div>
</div>

app/views/layouts/_messagePanelForm.html.erb
<div class="modal fade" id="messagePanel" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title"><b>New recieved smiles</b><span>&nbsp;&nbsp;</span><span class="badge">0</span> <span class="fa fa-eye-slash" style="float: right">Mark as read</span></h4>
      </div>
      <div class="modal-body">
        <table class="unreadMessages table table-hover">


        </table>         
       </div>

       <nav>
          <ul class="pager" id="messagePanelPager">
             <li class="previous"><a><span aria-hidden="true">&larr;&nbsp;</span>Previous</a></li>
             <li class="next"><a>Next<span aria-hidden="true">&nbsp;&rarr;</span></a></li>
          </ul>
       </nav>

       <div class="modal-footer"> 
         <a href="/messages"  class="readAllMessagesLink"><div class="readAllMessages">Read all</div></a>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_settingPanel.html.erb
<div class="modal fade" id="settingPanel" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
  <div class="modal-dialog">
    <div class="modal-content" id="settingBody">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" id="closePostModal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel"><b>Setting</b></h4>
      </div>

      <div class="modal-body">    
        <% if signed_in? %>
            <div id="avatarContainer">
              <% if current_user.avatar == nil %>
                <img src="http://7u2ew1.com1.z0.glb.clouddn.com/emptyAvatar.jpg">
              <%else%>
                <img src="<%= current_user.avatar%>">  
              <%end%>

              <div id="previewPanel" class="img-rounded">
              <div class="previewContainer">
              <% if current_user.avatar == nil %>
                <img src="http://7u2ew1.com1.z0.glb.clouddn.com/emptyAvatar.jpg" class="jcrop-preview">
              <%else%>
                <img src="<%= current_user.avatar%>/thumbnail/80x" class="jcrop-preview">  
              <%end%>
              </div>
            </div>
             
            </div>

            <div id="uploadNewPictureBtn">
                <button type="button" class="btn btn-default" id="uploadNewPicture">Upload new picture</button>
                <input type="file" id="avatar" >
            </div> 

            
        <% end %>
    </div>
      
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="saveChange">Save</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if it IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_signUpForm.html.erb
<div class="modal fade" id="signUp" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel"><b>Sign Up </b>to find who is smiling at you.</h4>
      </div>
      <div class="modal-body">
        <div id="signUpErrors">
        </div>
        <div class="signUpForm">
           <%= form_for User.new do |f| %>

             <%= f.label :name, "Name:" %>
             <%= f.text_field :name,  class: 'form-control signUpInputControl'  %><br>

             <%= f.label :gender, "Gender:" %>
             <div class="radio">

             <label class="radio-inline">
             <%= radio_button_tag(:gender,"male")%> <span class="fa fa-male"></span>
             </label>
             
             <label class="radio-inline">
             <%= radio_button_tag(:gender,"female") %><span class="fa fa-female"></span>
             </label>
             </div><br>


             <%= f.label :email, "Email:" %>
             <%= f.text_field :email, class: 'form-control signUpInputControl'  %><br>

             <%= f.label :password, "Password:" %>
             <%= f.password_field :password, class: 'form-control signUpInputControl'  %><br>

             <%= f.label :password_confirmation, "Confirmation:" %>
             <%= f.password_field :password_confirmation, class: 'form-control signUpInputControl'  %>
       
           <% end %>
          
        </div>          
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="sureToCreate">Create</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_smileAtForm.html.erb
<div class="modal fade" id="smileAtSb" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel"></h4>
      </div>
      <div class="modal-body">
      <b>Chose a smile:</b>
        <div class="row">
          <div class="col-md-12" id="uploadedSmiles">

          
          </div>
        </div>          
      </div>
        <nav>
          <ul class="pager" id="smileAtSbPager">
             <li class="previous"><a><span aria-hidden="true">&larr;&nbsp;</span>Previous</a></li>
             <span class="smileAtSbPercentage"></span>
             <li class="next"><a>Next<span aria-hidden="true">&nbsp;&rarr;</span></a></li>
          </ul>
        </nav>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="sureToSend">Send</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_uploadSmileForm.html.erb
<div class="modal fade" id="postsmile" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" id="closePostModal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel"><b>Upload your smile</b></h4>
      </div>
      <div class="modal-body">
        <div id="uploadArea">
           
        </div>   
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="sureToPost" style="visibility: hidden">Post</button>
      </div>
    </div>
  </div>
</div>